M48
; DRILL file {KiCad (6.0.7)} date Tue Jan 10 20:32:14 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-10T20:32:14-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X2.9475Y-3.3047
X3.4152Y-1.617
X4.4272Y-2.693
X4.8255Y-4.1615
X6.1377Y-5.6469
X6.5042Y-2.365
T0
M30
